### ISSUE TITLE
Prevent org deletion when it has one or more members

### ISSUE THREAD

**Issue by gnarea** [relaycorp/veraid-authority#123]
We're currently leaving orphan records behind, but instead of manually cascading the delete operation (which in itself is a major undertaking with MongoDB due to the lack of foreign key constraints), we should just prevent its deletion.

So org admins should first manually delete each member, which won't be easy until #122 is implemented.

**Comment by levansuper** [comment]
If there are no members and you are an admin you can delete the org. And in the process the last member should also be deleted
